FROM node:18.14.2 as build

WORKDIR /app

COPY . ./
RUN yarn && yarn build:api

FROM node:18.14.2-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 3000
ENTRYPOINT [ "node", "/app/dist/apps/api/main.js" ]
