version: "3.7"

services:
  api:
    image: api:latest
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - "3000:3000"
    environment:
      - CONFIG_FILE=/config.yaml
